name: iOS CI/CD for Trackizer App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Install CocoaPods (if applicable)
        run: pod install --repo-update
        working-directory: ./ # Change if Podfile is in a subfolder

      - name: Build the App
        run: |
          xcodebuild clean build \
          -project "Trackizer.xcodeproj" \
          -scheme "Trackizer" \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'

      - name: Run tests
        run: |
          xcodebuild test \
          -project "Trackizer.xcodeproj" \
          -scheme "Trackizer" \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' | xcpretty
