name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use the latest available macOS version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build for Simulator
        run: |
          xcodebuild clean build -scheme Trackizer -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0'
