name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14  # Ensure the latest macOS version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build for Simulator
        run: |
          xcodebuild clean build -scheme Trackizer -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
