name: iOS CI/CD for Trackizer App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Xcode Version
        run: xcodebuild -version
        
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Build the App
        run: |
          xcodebuild clean build \
          -project "Trackizer.xcodeproj" \
          -scheme "Trackizer" \
          -destination "platform=iOS Simulator,name=iPhone 15"

      - name: Run tests
        run: |
          xcodebuild test \
          -project "Trackizer.xcodeproj" \
          -scheme "Trackizer" \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' | xcpretty

